# Generated by Django 5.2.8 on 2025-11-12 04:00

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('fecha_hora', models.DateTimeField()),
                ('categoria', models.CharField(choices=[('estudiantes', 'Estudiantes por Equipos'), ('interfacultades', 'Interfacultades por Equipos')], max_length=20)),
                ('activa', models.BooleanField(default=True)),
                ('en_curso', models.BooleanField(default=False, verbose_name='En curso')),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de finalización')),
            ],
            options={
                'verbose_name': 'Competencia',
                'verbose_name_plural': 'Competencias',
            },
        ),
        migrations.CreateModel(
            name='Juez',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='Usuario')),
                ('password', models.CharField(max_length=128, verbose_name='Contraseña')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='Nombre')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='Apellido')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Último login')),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jueces', to='app.competencia', verbose_name='Competencia')),
            ],
            options={
                'verbose_name': 'Juez',
                'verbose_name_plural': 'Jueces',
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('dorsal', models.IntegerField()),
                ('juez_asignado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos_asignados', to='app.juez')),
            ],
            options={
                'ordering': ['dorsal'],
                'unique_together': {('juez_asignado', 'dorsal')},
            },
        ),
        migrations.CreateModel(
            name='RegistroTiempo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_registro', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tiempo', models.BigIntegerField(help_text='Tiempo en milisegundos')),
                ('horas', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('minutos', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(59)])),
                ('segundos', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(59)])),
                ('milisegundos', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)])),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiempos', to='app.equipo')),
            ],
            options={
                'ordering': ['tiempo'],
                'indexes': [models.Index(fields=['equipo', 'tiempo'], name='app_registr_equipo__234598_idx')],
            },
        ),
    ]
