# Generated by Django 5.2.8 on 2025-11-19 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_registrotiempo_competencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoEquipo',
            fields=[
            ],
            options={
                'verbose_name': 'Resultado por Equipo',
                'verbose_name_plural': '📊 Resultados por Equipo',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app.equipo',),
        ),
    ]
